name: CI

on:
  push:

    branches: 
    - '*'
    tags:
    - '*'

  pull_request:
    branches:
    - '*'

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    - name: Get hash
      shell: cmd
      working-directory: ./
      run: echo %GITHUB_SHA% > hash.txt

    - name: Get tag
      shell: cmd
      working-directory: ./
      if: startsWith(github.ref, 'refs/tags/')
      run: echo %GITHUB_REF_NAME% > hash.txt

    - name: Build
      run: npm run build-pr --if-present

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Launcher
        path: ./build/fpPS4 Temmie's Launcher (2.0.0)/win64/